services:
  # MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: guided-gospel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      # Named volume mounted to the MySQL data directory
      - mysql_guided_gospel_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./
    container_name: guided-gospel-server
    restart: unless-stopped
    depends_on:
      - mysql-db
    ports:
      - "8000:8000"
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      EMAILJS_SERVICE_ID: ${EMAILJS_SERVICE_ID}
      EMAILJS_TEMPLATE_ID: ${EMAILJS_TEMPLATE_ID}
      EMAILJS_PRIVATE_KEY: ${EMAILJS_PRIVATE_KEY}
      EMAILJS_PUBLIC_KEY: ${EMAILJS_PUBLIC_KEY}
    develop:
      watch:
        - action: rebuild
          path: ./
          target: /app
volumes:
  mysql_guided_gospel_data:
